### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by maticzav** [graphcool/graphql-middleware#2]
As the title suggests this issue is used to find a great logo for `graphql-middleware`.

The best idea I got so far, which would also somehow reflect the name, is a group or three cartoon animals with the middle one wearing a GraphQL T-Shirt - something like npm’s wombat.

I would love to hear all the ideas you’ve come up with! 😄

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/38250439-1411cf04-374f-11e8-9490-1e2a18654745.png)

**Comment by maticzav** [comment]
@fabien0102 this actually really cool! I like the second one better, but the first one is no different - I like them both. Would love to hear @schickling ‘s thoughs on this too!

**Comment by schickling** [comment]
Thanks a lot for bringing this up! I really like the idea of @fabien0102. I think there should be a visual-only logo that works without "GraphQL Middleware" text part, therefore I'm rather a fan of the first suggestion.

Maybe @kuldar has some thoughts as well?

**Comment by kuldar** [comment]
I like the direction of the first logo. 👍 I agree with @schickling though, that it would be great if the symbol could stand on its own. I can try iterating a bit on the first concept to see if I can come up with some improvements.

**Comment by fabien0102** [comment]
@kuldar Just in case that you need the sources (even if it's really simple to recreate ^^)
[graphql-middleware-logo.zip](https://github.com/graphcool/graphql-middleware/files/1884388/graphql-middleware-logo.zip)

**Comment by fabien0102** [comment]
@kuldar Very nice iteration! Really like the ratio of yours propositions (mine was a little bit too rectangle ^^).  I think that my favorite is the `Logo v1`, simple and understable (and I also like the dash style for the idea of "flexibility" and "lightness" 😃 )

**Comment by kuldar** [comment]
I agree, I think v1 & v3 have more potential than others. I think v1 feels bit more like a full "stack" vs. the v3 feels bit like it's crossing off the GraphQL logo.  But I agree, that with v1, there's less super direct connection to GraphQL.

**Comment by schickling** [comment]
Great work @kuldar! I'm actually a big fan of v2 since it clearly shows how you can split up your GraphQL server into layers, v1 is also great though.

Other thoughts? :)

**Comment by maticzav** [comment]
I agree with @schickling, I don’t know why but v2 feels just very well put - maybe because it’s for some reason slightly similar to Prisma logo? 

Truly great ideas!

**Comment by harrysolovay** [comment]
![graphqlmiddlewaredesign](https://user-images.githubusercontent.com/4893548/38761823-ec2f227c-3f53-11e8-80f6-79b63b0be3a2.png)
What about something like this, which emphasizes the nature of middleware (sequential processing). The use of gradients, seamlessly transitioning between centers, with only two colors, is suggestive of the transformation of data between middleware (the center of the dots symbolizing individual pieces of middleware). This is just a rough concept. Let me know if y'all have ideas for its revision :) I'll continue to brainstorm.

**Comment by maticzav** [comment]
Hey @kuldar, could you provide me with the files of your designs? I think we should try `v2` first and see how it feels within the README - we can nevertheless still switch later on to `v1` or `v3` if needed, but I have high hopes for `v2`. What do you think?

**Comment by maticzav** [comment]
#3 Please do keep the thread going! I like the appearance of `v2` in README, but I would be more than happy to hear your thoughts as well!
